"""update store models

Revision ID: 25fd5d37fe6f
Revises: 3d8747f7baec
Create Date: 2022-08-02 10:55:46.898337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25fd5d37fe6f'
down_revision = '3d8747f7baec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('logo_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'logo_url')
    # ### end Alembic commands ###
