"""New Migration

Revision ID: 4fa4ce89ad27
Revises: 73fc44ffa57c
Create Date: 2022-08-25 09:53:39.367628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fa4ce89ad27'
down_revision = '73fc44ffa57c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('qr_code_url', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'stores', ['qr_code_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='unique')
    op.drop_column('stores', 'qr_code_url')
    # ### end Alembic commands ###
