"""update menu models

Revision ID: 54d13c25918d
Revises: 8e30a46df072
Create Date: 2022-08-02 21:04:45.628563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d13c25918d'
down_revision = '8e30a46df072'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
