"""update menu models

Revision ID: 73fc44ffa57c
Revises: e3970b6ea053
Create Date: 2022-08-04 16:29:04.014269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fc44ffa57c'
down_revision = 'e3970b6ea053'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'items', ['title', 'menu_id'])
    op.create_unique_constraint(None, 'items', ['image_url'])
    op.create_foreign_key(None, 'items', 'users', ['owner_id'], ['id'])
    op.create_unique_constraint(None, 'menus', ['title'])
    op.create_unique_constraint(None, 'menus', ['title', 'store_id'])
    op.create_unique_constraint(None, 'menus', ['image_url'])
    op.create_unique_constraint(None, 'stores', ['logo_url'])
    op.create_unique_constraint(None, 'stores', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='unique')
    op.drop_constraint(None, 'stores', type_='unique')
    op.drop_constraint(None, 'menus', type_='unique')
    op.drop_constraint(None, 'menus', type_='unique')
    op.drop_constraint(None, 'menus', type_='unique')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='unique')
    op.drop_constraint(None, 'items', type_='unique')
    op.drop_column('items', 'owner_id')
    # ### end Alembic commands ###
