"""update menu models

Revision ID: 8e30a46df072
Revises: 75a41ce5e5ad
Create Date: 2022-08-02 21:03:27.779539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e30a46df072'
down_revision = '75a41ce5e5ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
