"""updating  models

Revision ID: e3970b6ea053
Revises: 54d13c25918d
Create Date: 2022-08-03 16:19:50.907394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3970b6ea053'
down_revision = '54d13c25918d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
